export const config = {
  matcher: [
    '/data.json',
    '/data.json.bak',
    '/data.json.bak:rest(\\..+)',
    '/link-stats.json',
    '/link-stats.json.bak',
    '/link-stats.json.bak:rest(\\..+)',
    '/submissions.json',
    '/submissions.json.bak',
    '/submissions.json.bak:rest(\\..+)',
    '/ad_id_details.json',
    '/campaign_config.json',
    '/beidou-koc-monthly-data.json',
    '/users.json',
    '/.code-review-graph',
    '/.code-review-graph/:path*',
    '/tests/:path*',
    '/scripts/:path*',
    '/promo-copy/:path*',
    '/fetch_koc_data.py',
    '/run_fetch.py',
    '/orders',
    '/orders.html',
    '/admin',
    '/admin.html',
    '/book-admin',
    '/book-admin.html',
    '/migrate',
    '/migrate.html',
    '/nft-platform',
    '/nft-platform.html',
    '/dashboard',
    '/dashboard.html',
    '/leaderboard',
    '/leaderboard.html',
    '/book-submit',
    '/book-submit.html',
    '/book-wall',
    '/book-wall.html',
    '/discord-activity',
    '/discord-activity.html',
    '/version-notes',
    '/version-notes.html',
    '/anystories-api-info.md',
    '/beidou-api-info.md',
    '/CPS_PLAYBOOK_V2.md',
    '/DESIGN.md',
    '/PLATFORM_TECHNICAL_SPEC.md',
    '/SECURITY_QUICK_FIX.md',
    '/:document(.+\\.md)',
    '/ac-sdk.js',
  ],
};

export default function blockSensitiveStaticRoute() {
  return new Response('Not Found', {
    status: 404,
    headers: {
      'Cache-Control': 'private, no-store, max-age=0',
      'CDN-Cache-Control': 'no-store',
      'Content-Type': 'text/plain; charset=utf-8',
      'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
      'Referrer-Policy': 'no-referrer',
      'Vercel-CDN-Cache-Control': 'no-store',
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'DENY',
      'X-Robots-Tag': 'noindex, nofollow',
    },
  });
}
